Repository TYPO3-Documentation/TYPO3CMS-Reference-TSconfig, pull requests merged in 2022-06, with the labels that each got.

#257 Add subsection properties and local toctree to page TCEMAIN
  Documentation/PageTsconfig/TceMain.rst
Labels: backport 11.5, backport 10.4

#255 Add subsection properties and local toctree to page options
  Documentation/UserTsconfig/Options.rst
Labels: backport 11.5, backport 10.4

#254 Add subsection properties and local toctree to page admPanel
  Documentation/UserTsconfig/AdmPanel.rst
Labels: backport 11.5, backport 10.4

#253 Add subsection properties and local toctree to page TCEFORM
  Documentation/PageTsconfig/TceForm.rst
Labels: backport 11.5, backport 10.4

#252 Add subsection properties and local toctree to page options
  Documentation/PageTsconfig/Options.rst
Labels: backport 11.5, backport 10.4

#250 Add subsection properties and local toctree (to page RTE)
  Documentation/PageTsconfig/Rte.rst
Labels: backport 11.5, backport 10.4

#268 [TASK] Indent code blocks correctly
  Documentation/UsingSetting/UserTSconfig.rst
Labels: backport 11.5

#270 [BUGFIX] Add missing single quote in code example
  Documentation/UsingSetting/PageTSconfig.rst
Labels: backport 11.5

#271 [BUGFIX] Adjust example for overriding and modifying values
  Documentation/UsingSetting/PageTSconfig.rst
Labels: backport-required

#275 [TASK] Add new UserTS option impexp.enableExportForNonAdminUser
  Documentation/UserTsconfig/Options.rst
Labels: backport 11.5, backport 10.4
