Repository TYPO3-Documentation/TYPO3CMS-Reference-TSconfig, pull requests merged in 2023-10, with the labels that each got.

#372 [TASK] Use "TYPO3 Explained" instead of "Core API document"
  Documentation/Introduction/Index.rst
  Documentation/PageTsconfig/TceMain.rst
Labels: backport 11.5, backport 12.4

#375 [TASK] Revise "Setting user TSconfig" chapter
  Documentation/Settings.cfg
  Documentation/UsingSetting/UserTSconfig.rst
Labels: backport 11.5, backport 12.4

#383 [FEATURE] #101843 - Allow configuration of color palettes in FormEngine
  Documentation/Images/ManualScreenshots/ColorPalettes/ColorPalette.png
  Documentation/PageTsconfig/ColorPalettes.rst
  Documentation/PageTsconfig/Index.rst
  Documentation/PageTsconfig/TceForm.rst
Labels: changelog

#382 [FEATURE] #101807 - Automatic inclusion of user TSconfig of extensions
  Documentation/UserTsconfig/Options.rst
  Documentation/UsingSetting/UserTSconfig.rst
  Documentation/UsingSetting/_UserTSconfig/_ext_localconf.php
  Documentation/UsingSetting/_UserTSconfig/_ext_localconf_v12.php
Labels: changelog

#380 [TASK] Cleanup manuals
  Documentation/Settings.cfg
Labels: backport 12.4

#386 [TASK] Reference BeforeLoadedUserTsConfigEvent in "Setting user TSconfig" chapter
  Documentation/UsingSetting/UserTSconfig.rst
Labels: changelog

#387 [TASK] Add example for UserTS setup.default.moduleData
  Documentation/UserTsconfig/Setup.rst
Labels: backport 12.4

#388 Improve section on UserTS setup
  Documentation/UserTsconfig/Setup.rst
Labels: backport 12.4

#391 [DOCS] Mention TCAdefaults do not apply to flexforms
  Documentation/PageTsconfig/TcaDefaults.rst
Labels: backport 11.5, backport 12.4
