Repository TYPO3-Documentation/TYPO3CMS-Reference-TSconfig, pull requests merged in 2023-12, with the labels that each got.

#405 [TASK] #102440 - Merge EXT:t3editor into backend
  Documentation/Settings.cfg
Labels: changelog

#406 Use myext_pi1 instead of my_ext_pi1
  Documentation/PageTsconfig/TceForm.rst
  Documentation/UsingSetting/PageTSconfig.rst
Labels: backport 11.5, backport 12.4

#408 Remove section Overriding FlexForm settings
  Documentation/UsingSetting/PageTSconfig.rst
Labels: backport 11.5, backport 12.4

#409 Clarify overriding FlexForm in TCEFORM
  Documentation/PageTsconfig/TceForm.rst
Labels: backport 12.4

#414 [TASK] Use "confval" instead of "aspect" for user TSconfig -> options
  Documentation/UserTsconfig/Options.rst
Labels: backport 11.5, backport 12.4

#417 [TASK] #102499 - User TSconfig setting "overridePageModule" removed
  Documentation/UserTsconfig/Options.rst
Labels: changelog
