Repository TYPO3-Documentation/TYPO3CMS-Reference-TSconfig, pull requests merged in 2024-04, with the labels that each got.

#446 [TASK] Split up page TSconfig's mod properties
  Documentation/PageTsconfig/Mod.rst
  Documentation/PageTsconfig/Mod/Shared.rst
  Documentation/PageTsconfig/Mod/WebInfo.rst
  Documentation/PageTsconfig/Mod/WebLayout.rst
  Documentation/PageTsconfig/Mod/WebList.rst
  Documentation/PageTsconfig/Mod/WebTs.rst
  Documentation/PageTsconfig/Mod/WebView.rst
  Documentation/PageTsconfig/Mod/Wizards.rst
Labels: backport 11.5, backport 12.4

#448 [TASK] Improve details of overriding TCEFORM field config
  Documentation/PageTsconfig/TceForm.rst
Labels: backport 11.5, backport 12.4

#453 [TASK] Switch to confvals for mod.web_info
  Documentation/PageTsconfig/Mod/WebInfo.rst
Labels: backport 11.5, backport 12.4

#452 [TASK] Switch to confvals for mod.SHARED
  Documentation/PageTsconfig/Mod/Shared.rst
Labels: backport 11.5, backport 12.4

#457 [TASK] Remove "Disable item "Page Tsconfig" from example
  Documentation/PageTsconfig/Mod/WebInfo.rst
Labels: backport 12.4

#468 [TASK] Correct indentation and add title to example in TcaDefaults
  Documentation/PageTsconfig/TcaDefaults.rst
Labels: backport 11.5, backport 12.4

#465 [TASK] Switch to confvals for mod.web_view
  Documentation/PageTsconfig/Mod/WebView.rst
Labels: backport 12.4

#464 [TASK] Switch to confvals for options
  Documentation/PageTsconfig/Options.rst
Labels: backport-required, backport 12.4

#475 [TASK] Correct indentation and introduce anchors
  Documentation/PageTsconfig/Templates.rst
  Documentation/PageTsconfig/Tx.rst
Labels: backport 11.5, backport 12.4

#466 [TASK] Switch to confvals for mod.wizards
  Documentation/PageTsconfig/Mod/Wizards.rst
Labels: backport 12.4

#445 [TASK] Add test-docs to make file
  Makefile
Labels: backport 11.5, backport 12.4

#455 [TASK] Switch to confvals for mod.web_layout
  Documentation/PageTsconfig/Mod/WebLayout.rst
  Documentation/PageTsconfig/Mod/_backendLayouts-example.tsconfig
Labels: backport 12.4

#458 [TASK] Add .ddev/.gitignore file
  .ddev/.gitignore
Labels: backport 12.4

#467 [TASK] Switch to confvals for rte
  Documentation/PageTsconfig/Rte.rst
Labels: backport 11.5, backport 12.4

#469 [TASK] Switch to confvals for TCEFORM
  Documentation/PageTsconfig/TceForm.rst
Labels: backport 11.5, backport 12.4

#474 [TASK] Switch to confvals for TCEMAIN
  Documentation/PageTsconfig/TceMain.rst
Labels: backport 11.5, backport 12.4

#459 [TASK] Remove caption of code snippet
  Documentation/PageTsconfig/Mod/Shared.rst
Labels: backport 12.4

#486 [TASK] Improve user TSconfig options
  Documentation/UserTsconfig/Options.rst
Labels: backport 11.5, backport 12.4

#485 [TASK] Improve user TSconfig auth
  Documentation/UserTsconfig/Auth.rst
Labels: backport 11.5, backport 12.4

#488 [TASK] Improve user TSconfig
  Documentation/UserTsconfig/Index.rst
  Documentation/UserTsconfig/Page.rst
  Documentation/UserTsconfig/Permissions.rst
  Documentation/UserTsconfig/TcaDefaults.rst
  Documentation/UserTsconfig/Tx.rst
Labels: backport 11.5, backport 12.4

#489 [TASK] Improve General pages
  Documentation/Index.rst
  Documentation/Introduction/Index.rst
  Documentation/Sitemap.rst
Labels: backport 11.5, backport 12.4

#487 [TASK] Improve user TSconfig setup
  Documentation/UserTsconfig/Setup.rst
  Documentation/UserTsconfig/_Setup/_user-setup-default.tsconfig
Labels: backport 11.5, backport 12.4

#490 [TASK] Improve Condition page
  Documentation/UsingSetting/Conditions.rst
Labels: backport 11.5, backport 12.4

#463 Breaking: #97135 - web-info - Removed support for module handling based on TBE_M…
  Documentation/PageTsconfig/Mod.rst
  Documentation/PageTsconfig/Mod/WebInfo.rst
  Documentation/PageTsconfig/Mod/WebTs.rst
  Documentation/UsingSetting/UserTSconfig.rst
Labels: backport 12.4

#498 [BUGFIX] Resovle rendering warnings
  Documentation/PageTsconfig/TceForm.rst
Labels: backport 12.4

#502 [BUGFIX] Resolve duplicate link anchors
  Documentation/PageTsconfig/Rte.rst
Labels: backport 11.5, backport 12.4
