Repository TYPO3-Documentation/TYPO3CMS-Reference-TSconfig, pull requests merged in 2024-11, with the labels that each got.

#552 [BUGFIX] Fix links to former TypoScript in 45 min
  Documentation/Index.rst
Labels: backport 12.4, backport 13.4

#551 Clarify TCEFORM structure
  Documentation/PageTsconfig/TceForm.rst
Labels: backport 12.4, backport 13.4

#560 Overhaul Introduction
  Documentation/Introduction/Index.rst
Labels: backport 12.4, backport 13.4

#565 Fix "itemsLimitPerTable" / "itemsLimitSingleTable" ranges and clarify…
  Documentation/PageTsconfig/Mod/WebList.rst
Labels: backport 12.4, backport 13.4

#563 [BUGFIX] [!!!][TASK] Remove pageTree.backgroundColor
  Documentation/Images/ManualScreenshots/List/optionsPageTreeBackgroundColor.png
  Documentation/UserTsconfig/Options.rst
Labels: changelog

#564 [TASK] Mention tree.level starting at 1 not 0
  Documentation/UsingSetting/Conditions.rst
Labels: backport 12.4, backport 13.4

#568 [TASK] Site settings can be used as constants in TSconfig
  Documentation/UsingSetting/Syntax.rst
Labels: backport 12.4, backport 13.4

#566 [TASK] Update mod.SHARED.colPos_list
  Documentation/Images/ManualScreenshots/List/SimpleBackendLayout.png
  Documentation/Images/ManualScreenshots/Page/SimpleBackendLayoutInPageModule.png
  Documentation/Images/ManualScreenshots/Page/SimpleBackendLayoutLeftNotEditable.png
  Documentation/PageTsconfig/Mod/Shared.rst
  Documentation/PageTsconfig/Mod/WebLayout/_BackendLayout.tsconfig
  Documentation/PageTsconfig/Mod/_snippets/_mod.SHARED.colPos_list.tsconfig
Labels: backport 12.4, backport 13.4

#573 [TASK] Remove version 12 change information
  Documentation/PageTsconfig/Mod/WebInfo.rst
  Documentation/PageTsconfig/Mod/WebTs.rst
  Documentation/PageTsconfig/Options.rst
  Documentation/PageTsconfig/TceForm.rst
  Documentation/PageTsconfig/TceMain.rst
  Documentation/PageTsconfig/Templates.rst
  Documentation/UsingSetting/Conditions.rst
  Documentation/UsingSetting/PageTSconfig.rst
  Documentation/UsingSetting/Syntax.rst
Labels: backport 13.4

#578 [TASK] Add link to BeforeRecordDownloadPresetsAreDisplayedEvent
  Documentation/PageTsconfig/Mod/WebList.rst
Labels: backport 13.4
